gantt
    title PGC 1
    dateFormat  DD-MM-YYYY

    section Prazos
        matrícula           :p1, 14-02-2019, 21-02-2019
        formulário de orientação :p2, after p1, 22-02-2019
        avaliação parcial : p3, after p2, 17-03-2019
        envio do conceito: p4, after p3, 14-05-2019

    section Tarefas
       ontologias : t1, 07-03-2019, 14-03-2019
       políticas de acesso: t2, 10-03-2019, 14-03-2019
       sistemas ABE: t3, after t2, 28-03-2019
       monografia parcial / formalidades: t5, after t3, 06-05-2019
       protótipo inicial: t4, after t3, 14-05-2019