nomes = [
    'Médicos clínicos',
    'Médico infectologista',
    'Médico acupunturista',
    'Médico legista',
    'Médico nefrologista',
    'Médico alergista e imunologista',
    'Médico neurologista',
    'Médico angiologista',
    'Médico nutrologista',
    'Médico cardiologista',
    'Médico oncologista clínico',
    'Médico cancerologista pediátrico',
    'Médico Pediatra',
    'Médico Clínico',
    'Médico pneumologista',
    'Médico de família e comunidade',
    'Médico psiquiatra',
    'Médico dermatologista',
    'Médico reumatologista',
    'Médico sanitarista',
    'Médico do trabalho',
    'Médico da estratégia de Saúde da Família',
    'Médico em medicina de tráfego',
    'Médico anatomopatologista',
    'Médico em medicina intensiva',
    'Médico Anestesiologista',
    'Médico endocrinologista e metabologista',
    'Médico fisiatra',
    'Médico gastroenterologista',
    'Médico geneticista',
    'Médico geriatra',
    'Médico hematologista',
    'Médico homeopata',
    'Assistentes sociais e economistas domésticos',
    'Assistente Social',
    'Farmacêuticos',
    'Farmacêutico',
    'Médicos em especialidades cirúrgicas',
    'Médico em cirurgia vascular',
    'Médico cirurgião cardiovascular',
    'Médico cirurgião de cabeça e pescoço',
    'Médico cirurgião do aparelho digestivo',
    'Médico Cirurgião Geral',
    'Médico cirurgião pediátrico',
    'Médico cirurgião plástico',
    'Médico cirurgião torácico',
    'Médico Ginecologista e Obstetra',
    'Médico mastologista',
    'Médico neurocirurgião',
    'Médico oftalmologista',
    'Médico ortopedista e traumatologista',
    'Médico otorrinolaringologista',
    'Médico coloproctologista',
    'Médico urologista',
    'Médico cancerologista cirúrgico',
    'Médico cirurgião da mão',
    'Médicos',
    'Médico foniatra',
    'Médico Generalista Alopata',
    'Médico broncoesofalogista',
    'Médico hansenologista',
    'Enfermeiros e afins',
    'Outros enfermeiros',
    'Enfermeiro',
    'Enfermeiro auditor',
    'Enfermeiro de bordo',
    'Enfermeiro de centro cirúrgico',
    'Enfermeiro de terapia intensiva',
    'Enfermeiro do trabalho',
    'Enfermeiro nefrologista',
    'Enfermeiro neonatologista',
    'Enfermeiro obstétrico',
    'Enfermeiro psiquiátrico',
    'Enfermeiro puericultor e pediátrico',
    'Enfermeiro sanitarista',
    'Enfermeiro da estratégia de saúde da família',
    'sem CBO',
    'Enfermeiro Estomaterapeuta',
    'Fisioterapeuta respiratório',
    'Cirurgião dentista - disfunção temporomandibular e',
    'Cirurgião dentista - odontologia para pacientes co',
    'Cirurgião dentista - traumatologista bucomaxilofac',
    'Médico Cardiologista Intervencionista',
    'Médico em medicina preventiva e social',
    'Médico residente',
    'Fisioterapeutas',
    'Fisioterapeuta geral',
    'Fisioterapeuta neurofuncional',
    'Fisioterapeuta traumato-ortopédica funcional',
    'Fisioterapeuta osteopata',
    'Fisioterapeuta quiropraxista',
    'Fisioterapeuta acupunturista',
    'Fisioterapeuta esportivo',
    'Fisioterapeuta do trabalho',
    'Fonoaudiólogos',
    'Fonoaudiólogo',
    'Nutricionistas',
    'Nutricionista',
    'Cirurgiões-dentistas',
    'Cirurgião dentista - auditor',
    'Cirurgião dentista - clínico geral',
    'Cirurgião dentista - endodontista',
    'Cirurgião dentista - epidemiologista',
    'Cirurgião dentista - estomatologista',
    'Cirurgião dentista - implantodontista',
    'Cirurgião dentista - odontogeriatra',
    'Cirurgião dentista - odontologista legal',
    'Cirurgião dentista - odontopediatra',
    'Cirurgião dentista - ortopedista e ortodontista',
    'Cirurgião dentista - patologista bucal',
    'Cirurgião dentista - periodontista',
    'Cirurgião dentista - protesiólogo bucomaxilofacial',
    'Cirurgião dentista - protesista',
    'Cirurgião dentista - radiologista',
    'Cirurgião dentista - reabilitador oral',
    'Cirurgião dentista de saúde coletiva',
    'Cirurgião dentista - odontologia do trabalho',
    'Cirurgião dentista - dentística',
    'Cirurgião-dentista da estratégia de saúde da família',
    'Psicólogos e psicanalistas',
    'Psicólogo Educacional',
    'Psicólogo Clínico',
    'Psicólogo do Esporte',
    'Psicólogo Hospitalar',
    'Psicólogo Jurídico',
    'Psicólogo Social',
    'Psicólogo do trânsito',
    'Psicólogo do Trabalho',
    'Psicólogo acupunturista',
    'Médicos em medicina diagnóstica e terapêutica',
    'Médico citopatologista',
    'Médico em endoscopia',
    'Médico em medicina nuclear',
    'Médico em radiologia e diagnóstico por imagem',
    'Médico patologista',
    'Médico radioterapeuta',
    'Médico patologista clínico / medicina laboratorial',
    'Médico hiperbarista',
    'Médico neurofisiologista clínico',
    'Outras ocupações de Nível Superior Relacionados à Saúde',
    'Pesquisador em Biologia Ambiental',
    'Pesquisador em Biologia Animal',
    'Pesquisador em biologia de Microorganismos e Parasitas',
    'Pesquisador em Biologia Humana',
    'Pesquisador de Clinica Médica',
    'Pesquisador de Medicina Básica',
    'Pesquisador em Saúde Coletiva',
    'Pesquisador em Ciências Sociais e Humanas',
    'Pesquisador em Psicologia',
    'Físico',
    'Físico (medicina)',
    'Físico (nuclear e reatores)',
    'Químico',
    'Biólogo',
    'BioMédico',
    'Engenheiro Agrícola',
    'Engenheiro Agrônomo',
    'Médico veterinário',
    'Terapeuta ocupacional',
    'Ortoptista',
    'Preparador Físico',
    'Professor da Educação de Jovens e Adulto',
    'Professor de educação física do ensino fundamental',
    'Professor de Artes no Ensino Médio',
    'Professor de Artes no Ensino Médio',
    'Professor de educação física no ensino superior',
    'Professor de Nutrição',
    'Professor de Terapia Ocupacional',
    'Professor de alunos com deficiência auditiva e surdos',
    'Professor de alunos com deficiência física',
    'Professor de alunos com deficiência múltipla',
    'Professor de alunos com deficiência visual',
    'Coordenador Pedagógico',
    'Orientador Educacional',
    'Pedagogo',
    'Professor de técnicas e Recursos Audiovisuais',
    'Psicopedagogo',
    'Neuropsicólogo',
    'Psicanalista',
    'Musicólogo',
    'Técnicos e auxiliares de enfermagem',
    'Técnico de enfermagem',
    'Técnico de enfermagem de terapia intensiva',
    'Técnico de enfermagem do trabalho',
    'Técnico de enfermagem psiquiátrica',
    'Auxiliar de Enfermagem',
    'Auxiliar de Enfermagem do Trabalho',
    'Auxiliar de enfermagem da estratégia de saúde da família',
    'Técnico de enfermagem de saúde da família',
    'Trabalhadores em serviços de promoção e apoio à saúde',
    'Visitador Sanitário',
    'sem CBO',
    'Socorrista (exceto médicos e enfermeiros) habilita',
    'Auxiliar de laboratório de análises físico-química',
    'Técnico de laboratório de análises físico-químicas',
    'Auxiliar de Radiologia (Revelação Fotográfica)',
    'Técnico em farmácia e em manipulação farmacêutica',
    'Auxiliar técnico em laboratório de farmácia',
    'Técnico em Laboratório de Farmácia',
    'Técnico em Farmácia',
    'Supervisores de produção em indústrias de produtos farmacêuticos, cosméticos e afins',
    'Mestre de produção farmacêutica',
    'Auxiliares de laboratório da saúde',
    'Auxiliar de banco de sangue',
    'Auxiliar de Farmácia de Manipulação',
    'Auxiliar de Laboratório de Análises Clínicas',
    'Auxiliar de Laboratório de Imunobiológicos',
    'Auxiliar de Produção Farmacêutica',
    'Técnicos de apoio à biotecnologia',
    'Técnico em Imunobiológicos',
    'Técnicos de laboratórios de saúde e bancos de sangue',
    'Técnico em patologia clínica',
    'Auxiliar Técnico em Patologia Clínica',
    'Nutricionistas',
    'Dietista',
    'Técnicos em próteses ortopédicas',
    'Técnico de ortopedia',
    'Técnicos em fotônica',
    'Técnico em reabilitação',
    'Técnico em equipamento médico hospitalar',
    'Técnicos de imobilizações ortopédicas',
    'Técnico de imobilização ortopédica',
    'Técnicos de odontologia',
    'Técnico em saúde bucal',
    'Protético Dentário',
    'Auxiliar de Prótese Dentária',
    'Agentes da saúde e do meio ambiente',
    'Agente de defesa ambiental',
    'Tecnólogos e técnicos em métodos de diagnósticos e terapêutica',
    'Técnico em radiologia e imagenologia',
    'Técnicos em biologia',
    'Técnico em Histologia',
    'Outras ocupações de Nível Técnico e Auxiliar em Saúde',
    'Técnico de Desporto Individual e Coletivo',
    'Professor de Alunos Com Deficiência Menta',
    'Musico Intérprete Cantor',
    'Musico Intérprete Instrumentista',
    'Ministro de Culto Religioso',
    'Técnico Químico',
    'Técnico de Saneamento',
    'Técnico em Laboratório Óptico',
    'Técnico em acupuntura',
    'Quiropraxista Cinesoterapeuta Eutonista',
    'Instrumentador Cirúrgico',
    'Auxiliar de Saúde (Navegação Marítima)',
    'Técnico em Óptica e Optometria Contatólog',
    'Técnico em Métodos Eletrográficos em Ence',
    'Técnico em Métodos Gráficos em Cardiologia',
    'Técnico de Alimentos',
    'Professor de Nível Médio Na Educação Inf',
    'Auxiliar de Desenvolvimento Infantil',
    'Professor de Nível Médio No Ensino Profis',
    'Instrutor de Cursos Livres',
    'Recreador',
    'Artista de Circo (Outros)',
    'Mecânico de manutenção e instalação de aparelhos de climatização e refrigeração',
    'Mecânico de manutenção de máquinas, em geral',
    'Mecânico de manutenção de automóveis, motocicletas e veículos similares',
    'Auxiliar geral de conservação de vias permanentes (exceto trilhos)',
    'Trabalhadores em serviços de promoção e apoio à saúde',
    'Agente comunitário de saúde',
    'Parteira leiga',
    'Agentes da saúde e do meio ambiente',
    'Agente de saúde pública',
    'Atendente de Enfermagem/Auxiliar operacional de serviços diversos e assemelhados',
    'Atendente de consultório dentário',
    'Atendente de enfermagem',
    'Atendente de farmácia - balconista',
    'Outras ocupações de Nível Elementar em Saúde',
    'Gesseiro',
    'Artesão modelador (vidros)',
    'Administração',
    'Diretor administrativo',
    'Diretor administrativo e financeiro',
    'Diretor financeiro',
    'Diretor de recursos humanos',
    'Diretor de relações de trabalho',
    'Diretor comercial',
    'Diretor de marketing',
    'Diretor de suprimentos',
    'Diretor de suprimentos no serviço publico',
    'Diretor de serviços de informática',
    'Diretor de pesquisa e desenvolvimento (p\&d)',
    'Diretor de manutenção',
    'Diretor de serviços culturais',
    'Diretor de serviços sociais',
    'Gerente de serviços culturais',
    'Gerente de serviços sociais',
    'Diretor de serviços de saúde',
    'Gerente de serviços de saúde',
    'Gerente de produção e operações',
    'Gerente administrativo',
    'Gerente de riscos',
    'Gerente financeiro',
    'Gerente de recursos humanos',
    'Gerente de departamento pessoal',
    'Gerente comercial',
    'Gerente de comunicação',
    'Gerente de marketing',
    'Gerente de vendas',
    'Gerente de compras',
    'Gerente de suprimentos',
    'Gerente de almoxarifado',
    'Gerente de rede',
    'Gerente de desenvolvimento de sistemas',
    'Gerente de operação de tecnologia da informação',
    'Gerente de projetos de tecnologia da informação',
    'Gerente de segurança da informação',
    'Gerente de suporte técnico de tecnologia da informação',
    'Gerente de pesquisa e desenvolvimento (p\&d)',
    'Gerente de projetos e serviços de manutenção',
    'Matemático',
    'Administrador de banco de dados',
    'Administrador de sistemas operacionais',
    'Analista de redes e de comunicação de dados',
    'Analista de suporte computacional',
    'Arquiteto de edificações',
    'Engenheiro civil',
    'Engenheiro civil (saneamento)',
    'Engenheiro de segurança do trabalho',
    'Professor de computação (no ensino superior)',
    'Advogado',
    'Advogado de empresa',
    'Economista domestico',
    'Administrador',
    'Auditor (contadores e afins)',
    'Contador',
    'Secretário executivo',
    'Analista financeiro (instituições financeiras)',
    'Fiscal de tributos municipal',
    'Arquivista',
    'Técnico eletrônico',
    'Técnico em manutenção de equipamentos de informática',
    'Técnico de manutenção de sistemas e instrumentos',
    'Programador de sistemas de informação',
    'Operador de computador',
    'Técnico de suporte ao usuário de tecnologia da informação',
    'Técnico de contabilidade',
    'Chefe de contabilidade (técnico)',
    'Técnico em Administração',
    'Técnico em secretariado',
    'Técnico em segurança do trabalho',
    'Comprador',
    'Supervisor de compras',
    'Supervisor administrativo',
    'Supervisor de almoxarifado',
    'Supervisor de contas a pagar',
    'Supervisor de controle patrimonial',
    'Supervisor de tesouraria',
    'Auxiliar de escritório',
    'Assistente técnico administrativo',
    'Auxiliar de pessoal',
    'Auxiliar de estatística',
    'Datilografo',
    'Digitador',
    'Continuo',
    'Auxiliar de contabilidade',
    'Auxiliar de faturamento',
    'Atendente de agencia',
    'Almoxarife',
    'Arquivista de documentos',
    'Supervisor de recepcionistas',
    'Cobrador externo',
    'Recepcionista, em geral',
    'Atendente de ambulatório ou clínica',
    'Telefonista',
    'Operador de rádiochamada',
    'Operador de telemarketing ativo e receptivo',
    'Operador de telemarketing técnico',
    'Supervisor de transportes',
    'Supervisor de andar',
    'Serviço de Limpeza/Conservação',
    'Agente de higiene e segurança',
    'Empregado doméstico nos serviços gerais',
    'Zelador de edifício',
    'Lavadeiro, em geral',
    'Lavador de roupas à máquina',
    'Passador de roupas em geral',
    'Atendente de lavanderia',
    'Auxiliar de lavanderia',
    'Jardineiro',
    'Pedreiro',
    'Eletricista de instalações',
    'Servente de obras',
    'Pintor a pincel e rolo (exceto obras e estruturas metálicas)',
    'Encanador',
    'Ajustador mecânico',
    'Marceneiro',
    'Operador de caldeira',
    'Segurança',
    'Guarda-civil municipal',
    'Agente de segurança',
    'Agente de segurança penitenciária',
    'Vigilante',
    'Porteiro de edifícios',
    'Vigia',
    'Guardador de veículos',
    'Agente de pátio',
    'Outras ocupações administrativas',
    'Cozinheiro geral',
    'Cozinheiro de hospital',
    'Cozinheiro de embarcações',
    'Copeiro',
    'Copeiro de hospital',
    'Ascensorista',
    'Trabalhador de serviços de manutenção',
    'Costureira de reparação de roupas',
    'Costureiro na confecção em serie',
    'Acabador de calçados',
    'Motorista de carro de passeio',
    'Motorista de furgão ou veículo similar',
    'Cozinhador conservação de alimentos'
]
